apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
# give list of containers to run in the pod
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    # specify environment variables for the container to use to set up the database
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    ports:
    - containerPort: 5432