apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
# give list of containers to run in the pod and the ports to expose for each container
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379